### ISSUE TITLE
Repo sync fail with local manifest

### ISSUE THREAD

**Issue by joelmaxuel** [CM-zenfone2/CM-zenfone2_local_manifest#2]
I'm one of the kids following along (aside from the fact I'm in my thirties) :)...

Had a problem repopicking (first one wasn't found on server), up until then I had a hybrid of local manifest, with all the extra projects pasted in, but I thought I would use the one listed here fully.

After getting past the hump of it not recognizing "github" (had to define it with a remote tag), I get this error, and now I feel like I'm trying to fight my way out of a wet paper bag:

> Fetching projects:  95% (527/554)  Fetching project platform/external/tinyxml
> Fetching project platform/external/libssh2
> Fetching project platform/external/chromium_org/third_party/libjingle/source/talk
> Fetching project CM-zenfone2/android_hardware_intel_img_psb_video
> Fetching project android_external_iptables
> Fetching projects:  96% (532/554)  Fetching project android_packages_apps_Profiles
> Fetching project android_external_bash
> Fetching projects:  97% (538/554)  Fetching project android_hardware_qcom_audio
> Fetching projects:  98% (543/554)  Fetching project android_hardware_qcom_display
> Fetching project android_hardware_qcom_audio
> Fetching projects:  99% (549/554)  Fetching project android_hardware_qcom_audio
> fatal: Couldn't find remote ref refs/tags/android-5.1.1_r6
> fatal: Couldn't find remote ref refs/tags/android-5.1.1_r6
> fatal: Couldn't find remote ref refs/tags/android-5.1.1_r6
> fatal: Couldn't find remote ref refs/tags/android-5.1.1_r6
> error: Cannot fetch CM-zenfone2/proprietary_vendor_asus
> warn: --force-broken, continuing to sync
> error: Cannot fetch CM-zenfone2/android_hardware_intel_common_libmix
> warn: --force-broken, continuing to sync
> error: Cannot fetch CM-zenfone2/android_device_asus_Z00A
> warn: --force-broken, continuing to sync
> error: Cannot fetch CM-zenfone2/android_kernel_asus_moorefield
> warn: --force-broken, continuing to sync
> Fetching projects: 100% (554/554), done.  
> error: in `sync -f`: revision refs/tags/android-5.1.1_r6 in CM-zenfone2/android_device_asus_Z00A not found

Suggestions?  My distro and repo is up-to-date.

**Comment by joelmaxuel** [comment]
Update: used Noel's commit and got past the issue.

Now there is just this...

> android@cybaryme:~/zenfone2$ repopick 103773
> Applying change number 103773 ...
> ERROR: Change number 103773 was not found on the server
> android@cybaryme:~/zenfone2$

If I am not building for CM, rather  a CM-derivative, is this expected and should I add the necessary commits manually?

**Comment by jrior001** [comment]
I posted a manifest designed to build CM, with cherrypicks for CM. I your building something else your gonna have tweak things to your world.

In CM repopick is designed to grab open commits from CM gerrit. If your working somewhere else there's no telling what repopick is trying to pull from. You will need to visit each commit on CM gerrit and cherry-pick manually. 

http://review.cyanogenmod.org/#/c/103773/

**Comment by joelmaxuel** [comment]
Just came back to say, answered my own question (after trying CM's repopick.py).  I will pull in the four projects and apply the five commits manually.  Thanks for the help.
