### ISSUE TITLE
Explanation of first repopick (103773)?

### ISSUE THREAD

**Issue by joelmaxuel** [CM-zenfone2/CM-zenfone2_local_manifest#3]
Hello again,
I am dissecting repopick 103773, and I don't know much about python.  What it looks like though is that it is renaming hardware/ril to hardware/ril-caf when the branch ends with -caf.

> ```
>     elif project_path.startswith('hardware/ril'):
>         project_path = project_path.rstrip('-caf')
>         if project_branch.split('-')[-1] == 'caf':
>             project_path += '-caf'
> ```

Is this so the 12.1 branch and the 12.1-caf branch can coexist in the same tree?  I patched both branches, should I have only patched one?  Would a local manifest solution look like (if that's the case with the former and not the latter):

> remote name="joelmaxuel"
> fetch="git://github.com/joelmaxuel"
> revision="cm-12.1" /
> 
> remote name="joelmaxuel-caf"
> fetch="git://github.com/joelmaxuel"
> revision="cm-12.1-caf" /
> 
> project name="android_hardware_ril" path="hardware/ril" remote="joelmaxuel" /
> project name="android_hardware_ril" path="hardware/ril-caf" remote="joelmaxuel-caf" /

The big thing I am missing out on in my ROM is the mobile data and I think my neglect of this gerrit patch is the cause.

**Comment by joelmaxuel** [comment]
May already have my answer after looking at the master manifest.xml file, except for whether to use both patched RIL projects, or just ril:cm-12.1 (as that's what the gerrit patch 102725 was designed for).  Trying with both now, but it will be about 12 hours before I can report progress.

**Comment by joelmaxuel** [comment]
Solved. ;)

**Comment by jrior001** [comment]
Glad you figured it out, I just saw the emails. Repo pick is currently broken, and didn't handle the ril vs ril-caf properly. This resulted in our ril patch being applied to the ril-caf branch instead  when cherry-picked with repopick. This change fixes repopick. It has to done seperatly so the script can complete and reload again with proper code for the next set of repopicks.
