### ISSUE TITLE
How would I build (not with this-- with, say CM 12.1)

### ISSUE THREAD

**Issue by faddat** [CM-zenfone2/CM-zenfone2_local_manifest#6]
Here's what I've got going on so far:

first sync the cm 12.1 repository
build/envsetup.sh
repopick -t zenfone2_bringup 
...... what else am I missing?  Thank you!

**Comment by crpalmer** [comment]
Look at the cm-12.1 branch of this repo....

https://github.com/CM-zenfone2/CM-zenfone2_local_manifest/blob/cm-12.1/cherry-pick.txt#L21

**Comment by faddat** [comment]
Dear me!  Closing my other issue, too.  Thank you.

**Comment by faddat** [comment]
A hundred thanks @crpalmer.
